# Generated by Django 5.2.16 on 2026-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'cancelled')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='purchasing_post_approval_status_has_audit'),
        ),
    ]
