# Generated by Django 5.2.16 on 2026-09-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_purchasing_post_approval_status_has_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='unit_snapshot',
            field=models.CharField(choices=[('piece', 'Piece'), ('pair', 'Pair'), ('pack', 'Pack'), ('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('millilitre', 'Millilitre'), ('metre', 'Metre')], max_length=16),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_snapshot',
            field=models.CharField(blank=True, choices=[('piece', 'Piece'), ('pair', 'Pair'), ('pack', 'Pack'), ('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('millilitre', 'Millilitre'), ('metre', 'Metre')], max_length=16),
        ),
    ]
