# Generated by Django 5.2.16 on 2026-09-11 18:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0002_productvariant_low_stock_threshold_and_more'),
        ('purchasing', '0003_alter_goodsreceiptline_unit_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnPostingKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('operation_type', models.CharField(choices=[('return', 'Purchase return'), ('reversal', 'Purchase return reversal')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_posting_keys', to='businesses.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_number', models.CharField(max_length=40)),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('supplier_document_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='businesses.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_cancelled', to='businesses.businessmembership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_created', to='businesses.businessmembership')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_posted', to='businesses.businessmembership')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchasing.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchasing.supplier')),
                ('posting_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_return', to='purchasing.purchasereturnpostingkey')),
            ],
            options={
                'ordering': ('-return_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_reversals', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_reversals', to='businesses.business')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_reversal', to='purchasing.purchasereturnpostingkey')),
                ('purchase_return', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='purchasing.purchasereturn')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns_reversed', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('returned_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('sku_snapshot', models.CharField(blank=True, max_length=80)),
                ('unit_snapshot', models.CharField(blank=True, choices=[('piece', 'Piece'), ('pair', 'Pair'), ('pack', 'Pack'), ('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('millilitre', 'Millilitre'), ('metre', 'Metre')], max_length=16)),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('receipt_unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('supplier_reference_total', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24)),
                ('assigned_inventory_unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('inventory_value_delta', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='businesses.business')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchasing.purchasereturn')),
                ('receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='purchasing.goodsreceiptline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('purchase_return', 'receipt_line'), name='purchasing_unique_receipt_line_per_return'), models.CheckConstraint(condition=models.Q(('returned_quantity__gt', Decimal('0.000'))), name='purchasing_return_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('receipt_unit_cost__gte', Decimal('0.000000'))), name='purchasing_return_receipt_cost_nonnegative'), models.CheckConstraint(condition=models.Q(('supplier_reference_total__gte', Decimal('0.000000'))), name='purchasing_return_supplier_total_nonnegative'), models.CheckConstraint(condition=models.Q(('assigned_inventory_unit_cost__gte', Decimal('0.000000'))), name='purchasing_return_inventory_cost_nonnegative'), models.CheckConstraint(condition=models.Q(('inventory_value_delta__lte', Decimal('0.000000'))), name='purchasing_return_inventory_value_nonpositive')],
            },
        ),
        migrations.AddConstraint(
            model_name='purchasereturnpostingkey',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='purchasing_unique_return_posting_key_per_business'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnpostingkey',
            constraint=models.CheckConstraint(condition=models.Q(('operation_type__in', ['return', 'reversal'])), name='purchasing_return_posting_key_type_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('business', 'internal_number'), name='purchasing_unique_return_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'posted', 'reversed', 'cancelled'])), name='purchasing_return_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('posted_at__isnull', True), ('posted_by__isnull', True), ('posting_key__isnull', True)), models.Q(('posted_at__isnull', False), ('posted_by__isnull', False), ('posting_key__isnull', False)), _connector='OR'), name='purchasing_return_posting_fields_match'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False)), _connector='OR'), name='purchasing_return_cancellation_fields_match'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_by__isnull', True), ('posting_key__isnull', True), ('status', 'draft')), models.Q(('cancelled_by__isnull', False), ('posting_key__isnull', True), ('status', 'cancelled')), models.Q(('cancelled_by__isnull', True), ('posting_key__isnull', False), ('status__in', ('posted', 'reversed'))), _connector='OR'), name='purchasing_return_status_has_audit'),
        ),
    ]
