# Generated by Django 5.2.16 on 2026-09-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businessmembership_assigned_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('stock_employee', 'Stock employee')], max_length=16),
        ),
    ]
