# Generated by Django 5.2.16 on 2026-09-11 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0002_productvariant_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePostingKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('source_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_posting_keys', to='businesses.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_number', models.CharField(max_length=40)),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='businesses.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_cancelled', to='businesses.businessmembership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_created', to='businesses.businessmembership')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_posted', to='businesses.businessmembership')),
                ('posting_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_sale', to='sales.salepostingkey')),
            ],
            options={
                'ordering': ('-sale_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InternalReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_number', models.CharField(max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr')], max_length=16)),
                ('telebirr_reference', models.CharField(blank=True, max_length=120)),
                ('issued_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_receipts', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_receipts', to='businesses.business')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_receipts_issued', to='businesses.businessmembership')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='sales.sale')),
            ],
            options={
                'ordering': ('-issued_at',),
                'constraints': [models.UniqueConstraint(fields=('business', 'internal_number'), name='sales_unique_receipt_number_per_business'), models.CheckConstraint(condition=models.Q(('total_amount__gt', Decimal('0.00'))), name='sales_receipt_total_positive'), models.CheckConstraint(condition=models.Q(('payment_method__in', ['cash', 'telebirr'])), name='sales_receipt_payment_method_is_valid')],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('product_name_snapshot', models.CharField(max_length=180)),
                ('sku_snapshot', models.CharField(max_length=80)),
                ('unit_snapshot', models.CharField(choices=[('piece', 'Piece'), ('pair', 'Pair'), ('pack', 'Pack'), ('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('millilitre', 'Millilitre'), ('metre', 'Metre')], max_length=16)),
                ('selling_unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('assigned_inventory_unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('inventory_value_delta', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='businesses.business')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('sale', 'variant'), name='sales_unique_variant_per_sale'), models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.000'))), name='sales_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('selling_unit_price__gt', Decimal('0.00'))), name='sales_line_price_positive'), models.CheckConstraint(condition=models.Q(('line_total__gt', Decimal('0.00'))), name='sales_line_total_positive'), models.CheckConstraint(condition=models.Q(('assigned_inventory_unit_cost__gte', Decimal('0.000000'))), name='sales_line_inventory_cost_nonnegative'), models.CheckConstraint(condition=models.Q(('inventory_value_delta__lte', Decimal('0.000000'))), name='sales_line_inventory_value_nonpositive')],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('telebirr_reference', models.CharField(blank=True, max_length=120)),
                ('telebirr_reference_normalized', models.CharField(blank=True, max_length=120)),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments', to='businesses.business')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_payments_received', to='businesses.businessmembership')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='sales.sale')),
            ],
            options={
                'ordering': ('-posted_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'telebirr'])), name='sales_payment_method_is_valid'), models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='sales_payment_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('method', 'cash'), ('telebirr_reference', ''), ('telebirr_reference_normalized', '')), models.Q(('method', 'telebirr'), models.Q(('telebirr_reference', ''), _negated=True), models.Q(('telebirr_reference_normalized', ''), _negated=True)), _connector='OR'), name='sales_payment_reference_matches_method'), models.UniqueConstraint(condition=models.Q(('method', 'telebirr')), fields=('business', 'telebirr_reference_normalized'), name='sales_unique_telebirr_reference_per_business')],
            },
        ),
        migrations.AddConstraint(
            model_name='salepostingkey',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='sales_unique_posting_key_per_business'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'internal_number'), name='sales_unique_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'posted', 'cancelled'])), name='sales_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ['unpaid', 'paid'])), name='sales_payment_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='sales_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_status', 'paid'), ('posted_at__isnull', False), ('posted_by__isnull', False), ('posting_key__isnull', False), ('status', 'posted')), models.Q(('payment_status', 'unpaid'), ('posted_at__isnull', True), ('posted_by__isnull', True), ('posting_key__isnull', True), ('status__in', ('draft', 'cancelled'))), _connector='OR'), name='sales_posting_fields_match'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status__in', ('draft', 'posted'))), _connector='OR'), name='sales_cancellation_fields_match'),
        ),
    ]
