# Generated by Django 5.2.16 on 2026-09-11 20:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'cancelled')), models.Q(('status', 'posted'), ('total_amount__gt', Decimal('0.00'))), _connector='OR'), name='sales_posted_total_positive'),
        ),
    ]
