# Generated by Django 5.2.16 on 2026-09-12 07:09

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_alter_businessmembership_role"),
        ("catalog", "0002_productvariant_low_stock_threshold_and_more"),
        ("sales", "0002_sale_sales_posted_total_positive"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleReturnPostingKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.UUIDField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("return", "Return posting"), ("reversal", "Return reversal")],
                        max_length=16,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_return_posting_keys",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SaleReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("internal_number", models.CharField(max_length=40)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("sale_reversal", "Full sale reversal"),
                            ("customer_return", "Customer return"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("return_date", models.DateField(default=django.utils.timezone.localdate)),
                ("reason", models.TextField()),
                (
                    "total_refund_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=18),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns",
                        to="businesses.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns",
                        to="businesses.business",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns_cancelled",
                        to="businesses.businessmembership",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns_created",
                        to="businesses.businessmembership",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns_posted",
                        to="businesses.businessmembership",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.sale",
                    ),
                ),
                (
                    "posting_key",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_return",
                        to="sales.salereturnpostingkey",
                    ),
                ),
            ],
            options={
                "ordering": ("-return_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SaleReturnReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "refund_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("telebirr", "Telebirr")], max_length=16
                    ),
                ),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("telebirr_reference", models.CharField(blank=True, max_length=120)),
                ("posted_at", models.DateTimeField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_return_reversals",
                        to="businesses.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_return_reversals",
                        to="businesses.business",
                    ),
                ),
                (
                    "posting_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_reversal",
                        to="sales.salereturnpostingkey",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_returns_reversed",
                        to="businesses.businessmembership",
                    ),
                ),
                (
                    "sale_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="sales.salereturn",
                    ),
                ),
            ],
            options={
                "ordering": ("-posted_at",),
            },
        ),
        migrations.CreateModel(
            name="SaleRefundEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("telebirr", "Telebirr")], max_length=16
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("telebirr_reference", models.CharField(blank=True, max_length=120)),
                ("telebirr_reference_normalized", models.CharField(blank=True, max_length=120)),
                ("posted_at", models.DateTimeField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_refund_evidence",
                        to="businesses.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_refund_evidence",
                        to="businesses.business",
                    ),
                ),
                (
                    "refunded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_refunds_recorded",
                        to="businesses.businessmembership",
                    ),
                ),
                (
                    "sale_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund",
                        to="sales.salereturn",
                    ),
                ),
            ],
            options={
                "ordering": ("-posted_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("method__in", ["cash", "telebirr"])),
                        name="sales_refund_method_is_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", Decimal("0.00"))),
                        name="sales_refund_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("method", "cash"),
                                ("telebirr_reference", ""),
                                ("telebirr_reference_normalized", ""),
                            ),
                            models.Q(
                                ("method", "telebirr"),
                                models.Q(("telebirr_reference", ""), _negated=True),
                                models.Q(("telebirr_reference_normalized", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="sales_refund_reference_matches_method",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("method", "telebirr")),
                        fields=("business", "telebirr_reference_normalized"),
                        name="sales_unique_refund_reference_per_business",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InternalReturnReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("internal_number", models.CharField(max_length=40)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "refund_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("telebirr", "Telebirr")], max_length=16
                    ),
                ),
                ("telebirr_reference", models.CharField(blank=True, max_length=120)),
                ("issued_at", models.DateTimeField()),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_return_receipts",
                        to="businesses.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_return_receipts",
                        to="businesses.business",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_return_receipts_issued",
                        to="businesses.businessmembership",
                    ),
                ),
                (
                    "original_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_receipts",
                        to="sales.internalreceipt",
                    ),
                ),
                (
                    "sale_return",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="sales.salereturn",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "internal_number"),
                        name="sales_unique_return_receipt_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_amount__gt", Decimal("0.00"))),
                        name="sales_return_receipt_total_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("refund_method__in", ["cash", "telebirr"])),
                        name="sales_return_receipt_method_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SaleReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("returned_quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("product_name_snapshot", models.CharField(max_length=180)),
                ("sku_snapshot", models.CharField(max_length=80)),
                (
                    "unit_snapshot",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("pair", "Pair"),
                            ("pack", "Pack"),
                            ("kilogram", "Kilogram"),
                            ("gram", "Gram"),
                            ("litre", "Litre"),
                            ("millilitre", "Millilitre"),
                            ("metre", "Metre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "original_selling_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("refund_line_total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "original_assigned_inventory_unit_cost",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "inventory_value_delta",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_return_lines",
                        to="businesses.business",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="sales.saleline",
                    ),
                ),
                (
                    "sale_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salereturn",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_return_lines",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sale_return", "sale_line"),
                        name="sales_unique_sale_line_per_return",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("returned_quantity__gt", Decimal("0.000"))),
                        name="sales_return_line_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("original_selling_unit_price__gt", Decimal("0.00"))),
                        name="sales_return_line_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("refund_line_total__gt", Decimal("0.00"))),
                        name="sales_return_line_total_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("original_assigned_inventory_unit_cost__gte", Decimal("0.000000"))
                        ),
                        name="sales_return_line_cost_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("inventory_value_delta__gte", Decimal("0.000000"))),
                        name="sales_return_inventory_value_nonnegative",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="salereturnpostingkey",
            constraint=models.UniqueConstraint(
                fields=("business", "key"), name="sales_unique_return_key_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnpostingkey",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation_type__in", ["return", "reversal"])),
                name="sales_return_operation_type_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.UniqueConstraint(
                fields=("business", "internal_number"),
                name="sales_unique_return_number_per_business",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["sale_reversal", "customer_return"])),
                name="sales_return_purpose_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "posted", "reversed", "cancelled"])),
                name="sales_return_status_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_refund_amount__gte", Decimal("0.00"))),
                name="sales_return_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("posted_at__isnull", True),
                        ("posted_by__isnull", True),
                        ("posting_key__isnull", True),
                    ),
                    models.Q(
                        ("posted_at__isnull", False),
                        ("posted_by__isnull", False),
                        ("posting_key__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sales_return_posting_fields_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_at__isnull", True), ("cancelled_by__isnull", True)),
                    models.Q(("cancelled_at__isnull", False), ("cancelled_by__isnull", False)),
                    _connector="OR",
                ),
                name="sales_return_cancellation_fields_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cancelled_by__isnull", True),
                        ("posting_key__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("cancelled_by__isnull", False),
                        ("posting_key__isnull", True),
                        ("status", "cancelled"),
                    ),
                    models.Q(
                        ("cancelled_by__isnull", True),
                        ("posting_key__isnull", False),
                        ("status__in", ("posted", "reversed")),
                        ("total_refund_amount__gt", Decimal("0.00")),
                    ),
                    _connector="OR",
                ),
                name="sales_return_status_has_audit",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnreversal",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_method__in", ["cash", "telebirr"])),
                name="sales_return_reversal_method_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="salereturnreversal",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_amount__gt", Decimal("0.00"))),
                name="sales_return_reversal_amount_positive",
            ),
        ),
    ]
