# Generated by Django 5.2.16 on 2026-09-22 01:42

import apps.catalog.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('sales', '0003_salereturnpostingkey_salereturn_salereturnreversal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTelebirrProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_display_name', models.CharField(max_length=160)),
                ('merchant_identifier', models.CharField(max_length=120)),
                ('qr_source', models.FileField(blank=True, max_length=255, storage=apps.catalog.storage.catalog_media_storage, upload_to=apps.catalog.storage.telebirr_qr_upload_path)),
                ('qr_media_type', models.CharField(blank=True, max_length=32)),
                ('qr_width', models.PositiveIntegerField(default=0)),
                ('qr_height', models.PositiveIntegerField(default=0)),
                ('qr_size', models.PositiveBigIntegerField(default=0)),
                ('qr_sha256', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profile', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profiles', to='businesses.business')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profiles_confirmed', to='businesses.businessmembership')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profiles_removed', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('branch',),
            },
        ),
        migrations.CreateModel(
            name='BranchTelebirrEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('replaced', 'Replaced'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('removed', 'Removed')], max_length=16)),
                ('previous_sha256', models.CharField(blank=True, max_length=64)),
                ('resulting_sha256', models.CharField(blank=True, max_length=64)),
                ('merchant_display_name', models.CharField(max_length=160)),
                ('merchant_identifier', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profile_events', to='businesses.businessmembership')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profile_events', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telebirr_profile_events', to='businesses.business')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sales.branchtelebirrprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='branchtelebirrprofile',
            constraint=models.CheckConstraint(condition=models.Q(('qr_media_type', ''), ('qr_media_type', 'image/png'), _connector='OR'), name='sales_telebirr_qr_media_type_png'),
        ),
        migrations.AddConstraint(
            model_name='branchtelebirrprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('is_active', False), ('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='sales_telebirr_removal_evidence_matches'),
        ),
        migrations.AddConstraint(
            model_name='branchtelebirrprofile',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), models.Q(('qr_source', ''), _negated=True), models.Q(('qr_sha256', ''), _negated=True)), _connector='OR'), name='sales_active_telebirr_profile_is_confirmed'),
        ),
        migrations.AddConstraint(
            model_name='branchtelebirrevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['created', 'replaced', 'activated', 'deactivated', 'removed'])), name='sales_telebirr_event_action_valid'),
        ),
    ]
