# Generated by Django 5.2.16 on 2026-09-21 10:45

import apps.documents.storage
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0003_product_show_public_prices'),
        ('expenses', '0001_initial'),
        ('inventory', '0006_stockcountapproval_stockcountline_and_more'),
        ('purchasing', '0004_purchasereturnpostingkey_purchasereturn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('purchase', 'Supplier purchase document'), ('expense', 'Operating-expense document'), ('opening_stock', 'Opening-stock document')], max_length=24)),
                ('status', models.CharField(choices=[('quarantined', 'Quarantined'), ('available', 'Available'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='quarantined', max_length=24)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('total_size', models.PositiveBigIntegerField(default=0)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_documents', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captured_documents', to='businesses.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_cancelled', to='businesses.businessmembership')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_uploaded', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('source', models.FileField(max_length=255, storage=apps.documents.storage.document_storage, upload_to=apps.documents.storage.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Malicious'), ('error', 'Scanner error')], default='pending', max_length=16)),
                ('scan_engine', models.CharField(blank=True, max_length=120)),
                ('malware_signature', models.CharField(blank=True, max_length=180)),
                ('scan_error', models.CharField(blank=True, max_length=180)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_files', to='businesses.business')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='documents.captureddocument')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('preview', 'Preview'), ('download', 'Download')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_access_events', to='businesses.businessmembership')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_access_events', to='businesses.business')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='documents.captureddocument')),
                ('document_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='documents.documentfile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentTranscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_owner_confirmation', 'Awaiting owner confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=120)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('settlement_terms', models.CharField(blank=True, max_length=180)),
                ('expense_document_date', models.DateField(blank=True, null=True)),
                ('expense_payee', models.CharField(blank=True, max_length=180)),
                ('expense_description', models.TextField(blank=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expense_payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('telebirr', 'Telebirr')], max_length=16)),
                ('expense_telebirr_reference', models.CharField(blank=True, max_length=120)),
                ('confirmation_key', models.UUIDField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions', to='businesses.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions_cancelled', to='businesses.businessmembership')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions_confirmed', to='businesses.businessmembership')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions_created', to='businesses.businessmembership')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcriptions', to='documents.captureddocument')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions', to='expenses.expensecategory')),
                ('replacement_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='documents.documenttranscription')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions_submitted', to='businesses.businessmembership')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_transcriptions', to='purchasing.supplier')),
                ('target_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_document_transcription', to='expenses.operatingexpense')),
                ('target_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_document_transcription', to='purchasing.purchase')),
            ],
            options={
                'ordering': ('document', 'attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='DocumentTranscriptionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcription_lines', to='businesses.business')),
                ('target_purchase_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_document_line', to='purchasing.purchaseline')),
                ('target_stock_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_document_line', to='inventory.stockoperation')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='documents.documenttranscription')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcription_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='DocumentTranscriptionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('replaced', 'Replaced')], max_length=16)),
                ('snapshot', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcription_revisions', to='businesses.businessmembership')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_transcription_revisions', to='businesses.business')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='documents.documenttranscription')),
            ],
            options={
                'ordering': ('sequence',),
            },
        ),
        migrations.AddConstraint(
            model_name='captureddocument',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['purchase', 'expense', 'opening_stock'])), name='documents_kind_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='captureddocument',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['quarantined', 'available', 'rejected', 'cancelled'])), name='documents_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='captureddocument',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('fingerprint', ''), _negated=True), models.Q(('status', 'cancelled'), _negated=True)), fields=('business', 'fingerprint'), name='documents_unique_active_fingerprint_per_business'),
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='documents_unique_file_position'),
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 5)), name='documents_file_position_range'),
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status__in', ['pending', 'clean', 'infected', 'error'])), name='documents_scan_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentaccessevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['preview', 'download'])), name='documents_access_action_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscription',
            constraint=models.UniqueConstraint(fields=('document', 'attempt_number'), name='documents_unique_transcription_attempt'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'awaiting_owner_confirmation'))), fields=('document',), name='documents_one_active_transcription'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscription',
            constraint=models.UniqueConstraint(condition=models.Q(('confirmation_key__isnull', False)), fields=('business', 'confirmation_key'), name='documents_unique_confirmation_key'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscription',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'awaiting_owner_confirmation', 'confirmed', 'cancelled'])), name='documents_transcription_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscriptionline',
            constraint=models.UniqueConstraint(fields=('transcription', 'position'), name='documents_unique_transcription_line_position'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscriptionline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0'))), name='documents_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscriptionline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0'))), name='documents_line_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscriptionrevision',
            constraint=models.UniqueConstraint(fields=('transcription', 'sequence'), name='documents_unique_revision_sequence'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscriptionrevision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['created', 'updated', 'submitted', 'returned', 'confirmed', 'cancelled', 'replaced'])), name='documents_revision_action_is_valid'),
        ),
    ]
