# Generated by Django 5.2.16 on 2026-09-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('documents', '0001_initial'),
        ('expenses', '0001_initial'),
        ('purchasing', '0004_purchasereturnpostingkey_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureddocument',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documenttranscription',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='captureddocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='documents_cancellation_evidence_matches'),
        ),
        migrations.AddConstraint(
            model_name='documenttranscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='documents_transcription_cancellation_evidence_matches'),
        ),
    ]
