# Generated by Django 5.2.16 on 2026-09-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('documents', '0002_captureddocument_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='purge_reason',
            field=models.CharField(blank=True, choices=[('infected', 'Malware scan rejection'), ('cancelled_retention_expired', 'Cancelled-document retention expired')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='documentfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purge_reason', ''), ('purged_at__isnull', True)), models.Q(('purged_at__isnull', False), ('purge_reason__in', ['infected', 'cancelled_retention_expired'])), _connector='OR'), name='documents_purge_evidence_matches'),
        ),
    ]
