# Generated by Django 5.2.16 on 2026-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('documents', '0003_documentfile_purge_reason_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='captureddocument',
            name='documents_unique_active_fingerprint_per_business',
        ),
        migrations.AddConstraint(
            model_name='captureddocument',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('fingerprint', ''), _negated=True), models.Q(('status', 'cancelled'), _negated=True)), fields=('business', 'branch', 'kind', 'fingerprint'), name='documents_unique_active_capture_scope'),
        ),
    ]
