# Generated by Django 5.2.16 on 2026-09-21 13:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('sales', '0003_salereturnpostingkey_salereturn_salereturnreversal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSaleSyncKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('local_draft_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Offline payload hashes must be lowercase SHA-256 values.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_sale_sync_keys', to='businesses.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfflineSaleSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('needs_review', 'Needs review'), ('rejected', 'Rejected')], max_length=16)),
                ('offline_created_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField()),
                ('snapshot', models.JSONField(default=dict)),
                ('conflict_messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_sale_syncs', to='businesses.businessmembership')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_sale_syncs', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_sale_syncs', to='businesses.business')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_sync', to='sales.sale')),
                ('sync_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='offline.offlinesalesynckey')),
            ],
            options={
                'ordering': ('-synced_at', '-created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='offlinesalesynckey',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='offline_unique_sale_sync_key_per_business'),
        ),
        migrations.AddConstraint(
            model_name='offlinesalesynckey',
            constraint=models.UniqueConstraint(fields=('business', 'local_draft_id'), name='offline_unique_local_sale_draft_per_business'),
        ),
        migrations.AddConstraint(
            model_name='offlinesalesync',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['synced', 'needs_review', 'rejected'])), name='offline_sale_sync_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='offlinesalesync',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sale__isnull', False), ('status__in', ('synced', 'needs_review'))), models.Q(('sale__isnull', True), ('status', 'rejected')), _connector='OR'), name='offline_sale_sync_sale_matches_status'),
        ),
    ]
