# Generated by Django 5.2.16 on 2026-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinesalesync',
            name='conflict_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
