# Generated by Django 5.2.16 on 2026-09-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('offline', '0002_alter_offlinesalesync_conflict_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinesalesync',
            name='drafted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_sale_drafts_made', to='businesses.businessmembership'),
        ),
    ]
