# Generated by Django 5.2.16 on 2026-09-20 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0002_productvariant_low_stock_threshold_and_more'),
        ('sales', '0003_salereturnpostingkey_salereturn_salereturnreversal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('map_url', models.URLField(blank=True)),
                ('supported_languages', models.CharField(default='en', max_length=16)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=16)),
                ('allow_search_indexing', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_profile', to='businesses.business')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_profiles_published', to='businesses.businessmembership')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_profiles_suspended', to=settings.AUTH_USER_MODEL)),
                ('unpublished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_profiles_unpublished', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('display_name',),
                'permissions': [('review_public_verification', 'Can review public profile verification'), ('suspend_public_profile', 'Can suspend public profiles')],
            },
        ),
        migrations.CreateModel(
            name='PublicContactLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=16)),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_contact_links', to='businesses.business')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_links', to='public_profiles.publicbusinessprofile')),
            ],
            options={
                'ordering': ('display_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='PublicOpeningHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_opening_hours', to='businesses.business')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_hours', to='public_profiles.publicbusinessprofile')),
            ],
            options={
                'ordering': ('weekday',),
            },
        ),
        migrations.CreateModel(
            name='PublicProductIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_product_identities', to='businesses.business')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_identity', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='PublicProfileEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('profile_updated', 'Profile updated'), ('hours_updated', 'Opening hours updated'), ('contact_link_updated', 'Contact link updated'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('indexing_changed', 'Indexing changed'), ('product_visibility_changed', 'Product visibility changed'), ('verification_requested', 'Verification requested'), ('verification_decided', 'Verification decided'), ('verification_stale', 'Verification became stale')], max_length=40)),
                ('actor_kind', models.CharField(choices=[('membership', 'Business membership'), ('platform_staff', 'Platform staff'), ('system', 'System')], max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_profile_events', to='businesses.businessmembership')),
                ('actor_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_public_profile_events', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_profile_events', to='businesses.business')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='public_profiles.publicbusinessprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PublicReturnReceiptIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_return_receipt_identities', to='businesses.business')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_identity', to='sales.internalreturnreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='PublicSaleReceiptIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_sale_receipt_identities', to='businesses.business')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_identity', to='sales.internalreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='PublicStorefrontDailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_date', models.DateField()),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('shared', 'Shared link'), ('qr', 'QR code')], max_length=16)),
                ('metric', models.CharField(choices=[('profile_view', 'Profile view'), ('product_view', 'Product view')], max_length=16)),
                ('target_type', models.CharField(choices=[('profile', 'Profile'), ('product', 'Product')], max_length=16)),
                ('target_public_id', models.UUIDField()),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_storefront_metrics', to='businesses.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_daily_metrics', to='catalog.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_metrics', to='public_profiles.publicbusinessprofile')),
            ],
            options={
                'ordering': ('-local_date', 'metric', 'source'),
            },
        ),
        migrations.CreateModel(
            name='PublicVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_type', models.CharField(choices=[('contact', 'Contact reviewed'), ('location', 'Location reviewed'), ('business_document', 'Business document reviewed')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('request_reason', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_verification_requests', to='businesses.business')),
                ('parent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='public_profiles.publicverificationrequest')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_requests', to='public_profiles.publicbusinessprofile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_verification_requests', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PublicVerificationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_type', models.CharField(choices=[('contact', 'Contact reviewed'), ('location', 'Location reviewed'), ('business_document', 'Business document reviewed')], max_length=24)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('revoke', 'Revoke'), ('renew', 'Renew'), ('stale', 'Stale')], max_length=16)),
                ('evidence_reference', models.CharField(blank=True, max_length=200)),
                ('private_reason', models.TextField(max_length=1000)),
                ('public_reviewed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('subject_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_verification_decisions', to='businesses.business')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_decisions', to='public_profiles.publicbusinessprofile')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_verification_decisions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='public_profiles.publicverificationrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='publicbusinessprofile',
            constraint=models.CheckConstraint(condition=models.Q(('publication_status__in', ['draft', 'published', 'unpublished'])), name='public_profile_publication_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicbusinessprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_suspended', True), ('suspended_at__isnull', False), ('suspended_by__isnull', False), models.Q(('suspension_reason', ''), _negated=True)), models.Q(('is_suspended', False), ('suspended_at__isnull', True), ('suspended_by__isnull', True), ('suspension_reason', '')), _connector='OR'), name='public_profile_suspension_fields_match'),
        ),
        migrations.AddConstraint(
            model_name='publiccontactlink',
            constraint=models.UniqueConstraint(fields=('profile', 'link_type'), name='public_unique_contact_link_type'),
        ),
        migrations.AddConstraint(
            model_name='publiccontactlink',
            constraint=models.CheckConstraint(condition=models.Q(('link_type__in', ['facebook', 'instagram', 'telegram', 'tiktok', 'youtube', 'other'])), name='public_contact_link_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicopeninghour',
            constraint=models.UniqueConstraint(fields=('profile', 'weekday'), name='public_unique_opening_hour_per_weekday'),
        ),
        migrations.AddConstraint(
            model_name='publicopeninghour',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='public_opening_hour_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicopeninghour',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closes_at__isnull', True), ('is_closed', True), ('opens_at__isnull', True)), models.Q(('closes_at__isnull', False), ('is_closed', False), ('opens_at__isnull', False)), _connector='OR'), name='public_opening_hour_values_match_closed'),
        ),
        migrations.AddConstraint(
            model_name='publicprofileevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['profile_updated', 'hours_updated', 'contact_link_updated', 'published', 'unpublished', 'suspended', 'reinstated', 'indexing_changed', 'product_visibility_changed', 'verification_requested', 'verification_decided', 'verification_stale'])), name='public_profile_event_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicprofileevent',
            constraint=models.CheckConstraint(condition=models.Q(('actor_kind__in', ['membership', 'platform_staff', 'system'])), name='public_profile_event_actor_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicstorefrontdailymetric',
            constraint=models.UniqueConstraint(fields=('profile', 'local_date', 'source', 'metric', 'target_type', 'target_public_id'), name='public_unique_daily_metric_bucket'),
        ),
        migrations.AddConstraint(
            model_name='publicstorefrontdailymetric',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['direct', 'shared', 'qr'])), name='public_metric_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicstorefrontdailymetric',
            constraint=models.CheckConstraint(condition=models.Q(('metric__in', ['profile_view', 'product_view'])), name='public_metric_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicstorefrontdailymetric',
            constraint=models.CheckConstraint(condition=models.Q(('target_type__in', ['profile', 'product'])), name='public_metric_target_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicstorefrontdailymetric',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='public_metric_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='publicverificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('indicator_type__in', ['contact', 'location', 'business_document'])), name='public_verification_request_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicverificationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'withdrawn'])), name='public_verification_request_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicverificationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('profile', 'indicator_type'), name='public_unique_pending_verification_type'),
        ),
        migrations.AddConstraint(
            model_name='publicverificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('indicator_type__in', ['contact', 'location', 'business_document'])), name='public_verification_decision_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='publicverificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['approve', 'reject', 'revoke', 'renew', 'stale'])), name='public_verification_decision_action_valid'),
        ),
    ]
