# Generated by Django 5.2.16 on 2026-09-20 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('public_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publicverificationdecision',
            name='public_verification_decision_action_valid',
        ),
        migrations.AlterField(
            model_name='publicverificationdecision',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('revoke', 'Revoke'), ('renew', 'Renew'), ('expire', 'Expire'), ('stale', 'Stale')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='publicverificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['approve', 'reject', 'revoke', 'renew', 'expire', 'stale'])), name='public_verification_decision_action_valid'),
        ),
    ]
