# Generated by Django 5.2.16 on 2026-09-11 17:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0002_productvariant_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('average_unit_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('inventory_value', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='businesses.business')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('branch', 'variant'),
                'constraints': [models.UniqueConstraint(fields=('business', 'branch', 'variant'), name='inventory_unique_balance_per_branch_variant'), models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', Decimal('0.000'))), name='inventory_balance_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('average_unit_cost__gte', Decimal('0.000000'))), name='inventory_balance_cost_nonnegative'), models.CheckConstraint(condition=models.Q(('inventory_value__gte', Decimal('0.000000'))), name='inventory_balance_value_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening balance'), ('purchase_receipt', 'Purchase receipt'), ('adjustment_in', 'Positive adjustment'), ('adjustment_out', 'Negative adjustment')], max_length=24)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('value_delta', models.DecimalField(decimal_places=6, max_digits=24)),
                ('source_type', models.CharField(choices=[('stock_operation', 'Stock operation'), ('goods_receipt_line', 'Goods receipt line')], max_length=24)),
                ('source_id', models.UUIDField()),
                ('reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_posted', to='businesses.businessmembership')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='businesses.business')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-posted_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('business', 'source_type', 'source_id', 'variant'), name='inventory_unique_movement_source_variant'), models.CheckConstraint(condition=models.Q(('quantity_delta', Decimal('0.000')), _negated=True), name='inventory_movement_quantity_nonzero'), models.CheckConstraint(condition=models.Q(('unit_cost__gte', Decimal('0.000000'))), name='inventory_movement_unit_cost_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('quantity_delta__gt', Decimal('0.000')), ('value_delta__gte', Decimal('0.000000'))), models.Q(('quantity_delta__lt', Decimal('0.000')), ('value_delta__lte', Decimal('0.000000'))), _connector='OR'), name='inventory_movement_value_direction_matches'), models.CheckConstraint(condition=models.Q(('movement_type__in', ['opening', 'purchase_receipt', 'adjustment_in', 'adjustment_out'])), name='inventory_movement_type_is_valid'), models.CheckConstraint(condition=models.Q(('source_type__in', ['stock_operation', 'goods_receipt_line'])), name='inventory_source_type_is_valid')],
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('opening', 'Opening balance'), ('adjustment_in', 'Positive adjustment'), ('adjustment_out', 'Negative adjustment')], max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations_posted', to='businesses.businessmembership')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations', to='businesses.business')),
            ],
            options={
                'ordering': ('-posted_at',),
                'constraints': [models.UniqueConstraint(fields=('business', 'idempotency_key'), name='inventory_unique_operation_idempotency_per_business'), models.CheckConstraint(condition=models.Q(('operation_type__in', ['opening', 'adjustment_in', 'adjustment_out'])), name='inventory_operation_type_is_valid')],
            },
        ),
    ]
