# Generated by Django 5.2.16 on 2026-09-11 17:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0002_productvariant_low_stock_threshold_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity_on_hand', Decimal('0.000')), _negated=True), models.Q(('average_unit_cost', Decimal('0.000000')), ('inventory_value', Decimal('0.000000'))), _connector='OR'), name='inventory_zero_balance_has_zero_cost_and_value'),
        ),
    ]
