# Generated by Django 5.2.16 on 2026-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_alter_businessmembership_role"),
        ("catalog", "0002_productvariant_low_stock_threshold_and_more"),
        ("inventory", "0004_remove_inventorymovement_inventory_movement_type_is_valid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventorymovement",
            name="inventory_movement_type_is_valid",
        ),
        migrations.RemoveConstraint(
            model_name="inventorymovement",
            name="inventory_source_type_is_valid",
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("opening", "Opening balance"),
                    ("purchase_receipt", "Purchase receipt"),
                    ("purchase_return", "Purchase return"),
                    ("purchase_return_reversal", "Purchase return reversal"),
                    ("sale", "Sale"),
                    ("sale_return", "Sale return"),
                    ("sale_return_reversal", "Sale return reversal"),
                    ("adjustment_in", "Positive adjustment"),
                    ("adjustment_out", "Negative adjustment"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("stock_operation", "Stock operation"),
                    ("goods_receipt_line", "Goods receipt line"),
                    ("purchase_return_line", "Purchase return line"),
                    ("purchase_return_reversal", "Purchase return reversal"),
                    ("sale_line", "Sale line"),
                    ("sale_return_line", "Sale return line"),
                    ("sale_return_reversal", "Sale return reversal"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movement_type__in",
                        [
                            "opening",
                            "purchase_receipt",
                            "purchase_return",
                            "purchase_return_reversal",
                            "sale",
                            "sale_return",
                            "sale_return_reversal",
                            "adjustment_in",
                            "adjustment_out",
                        ],
                    )
                ),
                name="inventory_movement_type_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        [
                            "stock_operation",
                            "goods_receipt_line",
                            "purchase_return_line",
                            "purchase_return_reversal",
                            "sale_line",
                            "sale_return_line",
                            "sale_return_reversal",
                        ],
                    )
                ),
                name="inventory_source_type_is_valid",
            ),
        ),
    ]
