# Generated by Django 5.2.16 on 2026-09-12 15:10

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_alter_businessmembership_role"),
        ("catalog", "0002_productvariant_low_stock_threshold_and_more"),
        ("inventory", "0005_remove_inventorymovement_inventory_movement_type_is_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCountApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("approved_at", models.DateTimeField()),
                ("line_count", models.PositiveIntegerField()),
                ("positive_variance_line_count", models.PositiveIntegerField()),
                ("negative_variance_line_count", models.PositiveIntegerField()),
                ("zero_variance_line_count", models.PositiveIntegerField()),
                (
                    "total_inventory_value_adjustment",
                    models.DecimalField(decimal_places=6, max_digits=24),
                ),
                ("evidence_checksum", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ("-approved_at",),
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name_snapshot", models.CharField(max_length=160)),
                ("variant_label_snapshot", models.CharField(blank=True, max_length=200)),
                ("sku_snapshot", models.CharField(max_length=80)),
                ("stock_unit_snapshot", models.CharField(max_length=16)),
                ("system_quantity_snapshot", models.DecimalField(decimal_places=3, max_digits=18)),
                (
                    "average_unit_cost_snapshot",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("inventory_value_snapshot", models.DecimalField(decimal_places=6, max_digits=24)),
                (
                    "physical_quantity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
                ),
                (
                    "variance_quantity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
                ),
                ("variance_explanation", models.TextField(blank=True)),
                (
                    "assigned_count_adjustment_unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("exceptional_cost_evidence_note", models.TextField(blank=True)),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("product_name_snapshot", "sku_snapshot"),
            },
        ),
        migrations.CreateModel(
            name="StockCountLineRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "previous_quantity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
                ),
                ("replacement_quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("reason", models.TextField(blank=True)),
                ("revised_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("line", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="StockCountPostingKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.UUIDField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("start", "Start stock count"),
                            ("approve", "Approve stock count"),
                            ("reverse", "Reverse stock count"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockCountReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-reversed_at",),
            },
        ),
        migrations.CreateModel(
            name="StockCountReviewReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("returned_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("session", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="StockCountSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("counting", "Counting"),
                            ("submitted", "Submitted for review"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="counting",
                        max_length=16,
                    ),
                ),
                ("business_date", models.DateField()),
                ("count_method_note", models.TextField()),
                ("started_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="inventorymovement",
            name="inventory_movement_type_is_valid",
        ),
        migrations.RemoveConstraint(
            model_name="inventorymovement",
            name="inventory_source_type_is_valid",
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("opening", "Opening balance"),
                    ("purchase_receipt", "Purchase receipt"),
                    ("purchase_return", "Purchase return"),
                    ("purchase_return_reversal", "Purchase return reversal"),
                    ("sale", "Sale"),
                    ("sale_return", "Sale return"),
                    ("sale_return_reversal", "Sale return reversal"),
                    ("adjustment_in", "Positive adjustment"),
                    ("adjustment_out", "Negative adjustment"),
                    ("stock_count_adjustment_in", "Stock count adjustment in"),
                    ("stock_count_adjustment_out", "Stock count adjustment out"),
                    ("stock_count_reversal_in", "Stock count reversal in"),
                    ("stock_count_reversal_out", "Stock count reversal out"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("stock_operation", "Stock operation"),
                    ("goods_receipt_line", "Goods receipt line"),
                    ("purchase_return_line", "Purchase return line"),
                    ("purchase_return_reversal", "Purchase return reversal"),
                    ("sale_line", "Sale line"),
                    ("sale_return_line", "Sale return line"),
                    ("sale_return_reversal", "Sale return reversal"),
                    ("stock_count_line", "Stock count line"),
                    ("stock_count_reversal", "Stock count reversal"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movement_type__in",
                        [
                            "opening",
                            "purchase_receipt",
                            "purchase_return",
                            "purchase_return_reversal",
                            "sale",
                            "sale_return",
                            "sale_return_reversal",
                            "adjustment_in",
                            "adjustment_out",
                            "stock_count_adjustment_in",
                            "stock_count_adjustment_out",
                            "stock_count_reversal_in",
                            "stock_count_reversal_out",
                        ],
                    )
                ),
                name="inventory_movement_type_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorymovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        [
                            "stock_operation",
                            "goods_receipt_line",
                            "purchase_return_line",
                            "purchase_return_reversal",
                            "sale_line",
                            "sale_return_line",
                            "sale_return_reversal",
                            "stock_count_line",
                            "stock_count_reversal",
                        ],
                    )
                ),
                name="inventory_source_type_is_valid",
            ),
        ),
        migrations.AddField(
            model_name="stockcountapproval",
            name="approved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_counts_approved",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountapproval",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_approvals",
                to="businesses.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockcountapproval",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_approvals",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_lines",
                to="businesses.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_lines",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="counted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_lines_counted",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_lines",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockcountlinerevision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_line_revisions",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountlinerevision",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_line_revisions",
                to="businesses.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockcountlinerevision",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_line_revisions",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountlinerevision",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="inventory.stockcountline",
            ),
        ),
        migrations.AddField(
            model_name="stockcountpostingkey",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_posting_keys",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountapproval",
            name="posting_key",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_approval",
                to="inventory.stockcountpostingkey",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreversal",
            name="approval",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="inventory.stockcountapproval",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreversal",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_reversals",
                to="businesses.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreversal",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_reversals",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreversal",
            name="posting_key",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_reversal",
                to="inventory.stockcountpostingkey",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreversal",
            name="reversed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_counts_reversed",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreviewreturn",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_review_returns",
                to="businesses.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreviewreturn",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_review_returns",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreviewreturn",
            name="returned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_review_returns",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountsession",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_sessions",
                to="businesses.branch",
            ),
        ),
        migrations.AddField(
            model_name="stockcountsession",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_count_sessions",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="stockcountsession",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_counts_cancelled",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountsession",
            name="start_key",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="started_stock_count",
                to="inventory.stockcountpostingkey",
            ),
        ),
        migrations.AddField(
            model_name="stockcountsession",
            name="started_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_counts_started",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountsession",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_counts_submitted",
                to="businesses.businessmembership",
            ),
        ),
        migrations.AddField(
            model_name="stockcountreviewreturn",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_returns",
                to="inventory.stockcountsession",
            ),
        ),
        migrations.AddField(
            model_name="stockcountlinerevision",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_revisions",
                to="inventory.stockcountsession",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="inventory.stockcountsession",
            ),
        ),
        migrations.AddField(
            model_name="stockcountapproval",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval",
                to="inventory.stockcountsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountpostingkey",
            constraint=models.UniqueConstraint(
                fields=("business", "key"), name="inventory_unique_stock_count_key_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountpostingkey",
            constraint=models.CheckConstraint(
                condition=models.Q(("operation_type__in", ["start", "approve", "reverse"])),
                name="inventory_stock_count_key_operation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("counting", "submitted"))),
                fields=("business", "branch"),
                name="inventory_unique_open_stock_count_per_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["counting", "submitted", "approved", "cancelled"])
                ),
                name="inventory_stock_count_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("submitted_at__isnull", True), ("submitted_by__isnull", True)),
                    models.Q(("submitted_at__isnull", False), ("submitted_by__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_stock_count_submission_fields_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_at__isnull", True), ("cancelled_by__isnull", True)),
                    models.Q(("cancelled_at__isnull", False), ("cancelled_by__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_stock_count_cancellation_fields_match",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cancelled_by__isnull", True), ("status", "counting")),
                    models.Q(
                        ("cancelled_by__isnull", True),
                        ("status", "submitted"),
                        ("submitted_by__isnull", False),
                    ),
                    models.Q(
                        ("cancelled_by__isnull", True),
                        ("status", "approved"),
                        ("submitted_by__isnull", False),
                    ),
                    models.Q(("cancelled_by__isnull", False), ("status", "cancelled")),
                    _connector="OR",
                ),
                name="inventory_stock_count_status_has_audit",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountreviewreturn",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence"),
                name="inventory_unique_stock_count_review_return_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountlinerevision",
            constraint=models.UniqueConstraint(
                fields=("line", "sequence"), name="inventory_unique_stock_count_revision_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountlinerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_quantity__isnull", True),
                    ("previous_quantity__gte", Decimal("0.000")),
                    _connector="OR",
                ),
                name="inventory_stock_count_previous_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountlinerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("replacement_quantity__gte", Decimal("0.000"))),
                name="inventory_stock_count_replacement_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                fields=("session", "variant"), name="inventory_unique_stock_count_line_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(("system_quantity_snapshot__gte", Decimal("0.000"))),
                name="inventory_stock_count_system_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(("average_unit_cost_snapshot__gte", Decimal("0.000000"))),
                name="inventory_stock_count_average_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(("inventory_value_snapshot__gte", Decimal("0.000000"))),
                name="inventory_stock_count_value_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("physical_quantity__isnull", True),
                    ("physical_quantity__gte", Decimal("0.000")),
                    _connector="OR",
                ),
                name="inventory_stock_count_physical_quantity_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assigned_count_adjustment_unit_cost__isnull", True),
                    ("assigned_count_adjustment_unit_cost__gte", Decimal("0.000000")),
                    _connector="OR",
                ),
                name="inventory_stock_count_assigned_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("counted_at__isnull", True), ("counted_by__isnull", True)),
                    models.Q(("counted_at__isnull", False), ("counted_by__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_stock_count_counted_fields_match",
            ),
        ),
    ]
