# Generated by Django 5.2.16 on 2026-09-11 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_businessmembership_assigned_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=16)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='businesses.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-work_date', '-check_in_at', 'employee'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('previous_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=16)),
                ('replacement_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=16)),
                ('previous_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('previous_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to='businesses.business')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections_made', to='businesses.businessmembership')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('business', 'employee', 'work_date'), name='attendance_unique_employee_business_date'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_in_at__isnull', False), _connector='OR'), name='attendance_checkout_requires_checkin'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_out_at__gte', models.F('check_in_at')), _connector='OR'), name='attendance_checkout_not_before_checkin'),
        ),
    ]
