# Generated by Django 5.2.16 on 2026-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('businesses', '0002_businessmembership_assigned_branch'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['present', 'absent', 'excused'])), name='attendance_status_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('check_in_at__isnull', False), ('status', 'present')), models.Q(('check_in_at__isnull', True), ('check_out_at__isnull', True), ('status__in', ('absent', 'excused'))), _connector='OR'), name='attendance_status_matches_timestamps'),
        ),
    ]
