# Generated by Django 5.2.16 on 2026-09-11 17:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('pair', 'Pair'), ('pack', 'Pack'), ('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('millilitre', 'Millilitre'), ('metre', 'Metre')], default='piece', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock_unit__in', ['piece', 'pair', 'pack', 'kilogram', 'gram', 'litre', 'millilitre', 'metre'])), name='catalog_variant_stock_unit_is_valid'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__isnull', True), ('low_stock_threshold__gte', Decimal('0.000')), _connector='OR'), name='catalog_variant_low_stock_nonnegative'),
        ),
    ]
