# Generated by Django 5.2.16 on 2026-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_public_prices',
            field=models.BooleanField(default=False),
        ),
    ]
