# Generated by Django 5.2.16 on 2026-09-22 01:42

import apps.catalog.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('catalog', '0003_product_show_public_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.FileField(max_length=255, storage=apps.catalog.storage.catalog_media_storage, upload_to=apps.catalog.storage.product_image_upload_path)),
                ('media_type', models.CharField(max_length=32)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('alt_text', models.CharField(max_length=240)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='businesses.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='catalog.product')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images_removed', to='businesses.businessmembership')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images_uploaded', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductImageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('added', 'Added'), ('replaced', 'Replaced'), ('removed', 'Removed'), ('reconciled', 'Reconciled')], max_length=16)),
                ('previous_sha256', models.CharField(blank=True, max_length=64)),
                ('resulting_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_image_events', to='businesses.businessmembership')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_image_events', to='businesses.business')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_events', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('product',), name='catalog_one_current_image_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('width__gte', 1), ('height__gte', 1), ('size__gte', 1)), name='catalog_product_image_dimensions_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('media_type', 'image/webp')), name='catalog_product_image_media_type_webp'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='catalog_product_image_removal_evidence_matches'),
        ),
        migrations.AddConstraint(
            model_name='productimageevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['added', 'replaced', 'removed', 'reconciled'])), name='catalog_product_image_event_action_valid'),
        ),
    ]
