# Generated by Django 5.2.16 on 2026-09-12 13:03

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('cash', '0002_remove_cashmovement_cash_movement_type_valid_and_more'),
        ('purchasing', '0004_purchasereturnpostingkey_purchasereturn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='businesses.business')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExpenseSettlementPostingKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('operation_type', models.CharField(choices=[('expense', 'Operating expense'), ('expense_reversal', 'Operating expense reversal'), ('supplier_payment', 'Supplier payment'), ('supplier_payment_reversal', 'Supplier payment reversal'), ('return_settlement', 'Supplier return settlement'), ('return_settlement_reversal', 'Supplier return settlement reversal')], max_length=32)),
                ('source_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_settlement_posting_keys', to='businesses.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_number', models.CharField(max_length=40)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('payee', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses', to='businesses.business')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses_cancelled', to='businesses.businessmembership')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses_created', to='businesses.businessmembership')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses_posted', to='businesses.businessmembership')),
                ('posting_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_expense', to='expenses.expensesettlementpostingkey')),
            ],
            options={
                'ordering': ('-business_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OperatingExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('telebirr_reference', models.CharField(blank=True, max_length=120)),
                ('telebirr_reference_normalized', models.CharField(blank=True, max_length=120)),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_payments', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_payments', to='businesses.business')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_payments', to='cash.cashsession')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='expenses.operatingexpense')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_payments_posted', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='OperatingExpenseReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_reversals', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_reversals', to='businesses.business')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operating_expense_reversals', to='cash.cashsession')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='expenses.operatingexpense')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reversal', to='expenses.expensesettlementpostingkey')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operating_expenses_reversed', to='businesses.businessmembership')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr')], max_length=16)),
                ('supplier_reference', models.CharField(blank=True, max_length=120)),
                ('telebirr_reference', models.CharField(blank=True, max_length=120)),
                ('telebirr_reference_normalized', models.CharField(blank=True, max_length=120)),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='businesses.business')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='cash.cashsession')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_posted', to='businesses.businessmembership')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment', to='expenses.expensesettlementpostingkey')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='purchasing.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplier')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_reversals', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_reversals', to='businesses.business')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_reversals', to='cash.cashsession')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_reversal', to='expenses.expensesettlementpostingkey')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_reversed', to='businesses.businessmembership')),
                ('supplier_payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='expenses.supplierpayment')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('settlement_type', models.CharField(choices=[('credit', 'Credit accepted'), ('refund', 'Refund recovered')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('telebirr', 'Telebirr')], max_length=16)),
                ('supplier_reference', models.CharField(blank=True, max_length=120)),
                ('telebirr_reference', models.CharField(blank=True, max_length=120)),
                ('telebirr_reference_normalized', models.CharField(blank=True, max_length=120)),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlements', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlements', to='businesses.business')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlements', to='cash.cashsession')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlements_posted', to='businesses.businessmembership')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlement', to='expenses.expensesettlementpostingkey')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_settlements', to='purchasing.purchase')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_settlements', to='purchasing.purchasereturn')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_settlements', to='purchasing.supplier')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnSettlementReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlement_reversals', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlement_reversals', to='businesses.business')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlement_reversals', to='cash.cashsession')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlement_reversal', to='expenses.expensesettlementpostingkey')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_settlements_reversed', to='businesses.businessmembership')),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='expenses.supplierreturnsettlement')),
            ],
            options={
                'ordering': ('-posted_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('business'), name='expenses_unique_category_name_business'),
        ),
        migrations.AddConstraint(
            model_name='expensesettlementpostingkey',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='expenses_unique_posting_key_business'),
        ),
        migrations.AddConstraint(
            model_name='expensesettlementpostingkey',
            constraint=models.CheckConstraint(condition=models.Q(('operation_type__in', ['expense', 'expense_reversal', 'supplier_payment', 'supplier_payment_reversal', 'return_settlement', 'return_settlement_reversal'])), name='expenses_posting_operation_valid'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpense',
            constraint=models.UniqueConstraint(fields=('business', 'internal_number'), name='expenses_unique_number_business'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpense',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'posted', 'reversed', 'cancelled'])), name='expenses_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='expenses_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('business_date__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('posted_at__isnull', True), ('posted_by__isnull', True), ('posting_key__isnull', True), ('status', 'draft')), models.Q(('business_date__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('posted_at__isnull', False), ('posted_by__isnull', False), ('posting_key__isnull', False), ('status__in', ('posted', 'reversed'))), models.Q(('business_date__isnull', True), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('posted_at__isnull', True), ('posted_by__isnull', True), ('posting_key__isnull', True), ('status', 'cancelled')), _connector='OR'), name='expenses_lifecycle_evidence_matches'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'telebirr'])), name='expenses_payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='expenses_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpensepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_session__isnull', False), ('method', 'cash'), ('telebirr_reference', ''), ('telebirr_reference_normalized', '')), models.Q(('cash_session__isnull', True), ('method', 'telebirr'), models.Q(('telebirr_reference', ''), _negated=True), models.Q(('telebirr_reference_normalized', ''), _negated=True)), _connector='OR'), name='expenses_payment_evidence_matches'),
        ),
        migrations.AddConstraint(
            model_name='operatingexpensepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('method', 'telebirr')), fields=('business', 'telebirr_reference_normalized'), name='expenses_unique_payment_telebirr'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['cash', 'telebirr'])), name='expenses_supplier_payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='expenses_supplier_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_session__isnull', False), ('method', 'cash'), ('telebirr_reference', ''), ('telebirr_reference_normalized', '')), models.Q(('cash_session__isnull', True), ('method', 'telebirr'), models.Q(('telebirr_reference', ''), _negated=True), models.Q(('telebirr_reference_normalized', ''), _negated=True)), _connector='OR'), name='expenses_supplier_payment_evidence'),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('method', 'telebirr')), fields=('business', 'telebirr_reference_normalized'), name='expenses_unique_supplier_payment_ref'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('settlement_type__in', ['credit', 'refund'])), name='expenses_return_settlement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='expenses_return_settlement_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_session__isnull', True), ('method', ''), ('settlement_type', 'credit'), ('telebirr_reference', ''), ('telebirr_reference_normalized', '')), models.Q(('cash_session__isnull', False), ('method', 'cash'), ('settlement_type', 'refund'), ('telebirr_reference', ''), ('telebirr_reference_normalized', '')), models.Q(('cash_session__isnull', True), ('method', 'telebirr'), ('settlement_type', 'refund'), models.Q(('telebirr_reference', ''), _negated=True), models.Q(('telebirr_reference_normalized', ''), _negated=True)), _connector='OR'), name='expenses_return_settlement_evidence'),
        ),
        migrations.AddConstraint(
            model_name='supplierreturnsettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('method', 'telebirr'), ('settlement_type', 'refund')), fields=('business', 'telebirr_reference_normalized'), name='expenses_unique_supplier_refund_ref'),
        ),
    ]
