# Generated by Django 5.2.16 on 2026-09-12 09:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPostingKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.UUIDField()),
                ('operation_type', models.CharField(choices=[('open', 'Session opening'), ('manual_movement', 'Manual cash movement'), ('close', 'Session closing'), ('reopen', 'Session reopening')], max_length=24)),
                ('source_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_posting_keys', to='businesses.business')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='businesses.business')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_opened', to='businesses.businessmembership')),
                ('opening_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opened_session', to='cash.cashpostingkey')),
            ],
            options={
                'ordering': ('-business_date', '-opened_at'),
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('opening_float', 'Opening float'), ('cash_sale', 'Cash sale'), ('cash_refund', 'Cash refund'), ('cash_added', 'Cash added'), ('cash_removed', 'Cash removed')], max_length=24)),
                ('amount_delta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements_posted', to='businesses.businessmembership')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='businesses.business')),
                ('posting_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_cash_movement', to='cash.cashpostingkey')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cash.cashsession')),
            ],
            options={
                'ordering': ('posted_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CashSessionClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('explanation', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_session_closures', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_session_closures', to='businesses.business')),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_closed', to='businesses.businessmembership')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_session_closure', to='cash.cashpostingkey')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='cash.cashsession')),
            ],
            options={
                'ordering': ('session', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='CashSessionReopening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_session_reopenings', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_session_reopenings', to='businesses.business')),
                ('closure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reopening', to='cash.cashsessionclosure')),
                ('posting_key', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_session_reopening', to='cash.cashpostingkey')),
                ('reopened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_reopened', to='businesses.businessmembership')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reopenings', to='cash.cashsession')),
            ],
            options={
                'ordering': ('session', 'posted_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='cashpostingkey',
            constraint=models.UniqueConstraint(fields=('business', 'key'), name='cash_unique_posting_key_per_business'),
        ),
        migrations.AddConstraint(
            model_name='cashpostingkey',
            constraint=models.CheckConstraint(condition=models.Q(('operation_type__in', ['open', 'manual_movement', 'close', 'reopen'])), name='cash_posting_operation_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(fields=('business', 'branch', 'business_date'), name='cash_unique_session_per_branch_date'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('business', 'branch'), name='cash_unique_open_session_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'closed'])), name='cash_session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_float__gte', Decimal('0.00'))), name='cash_session_opening_float_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['opening_float', 'cash_sale', 'cash_refund', 'cash_added', 'cash_removed'])), name='cash_movement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_delta__gte', Decimal('0.00')), ('movement_type', 'opening_float'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'cash_sale'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'cash_refund'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'cash_added'), ('posting_key__isnull', False), ('source_id__isnull', True)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'cash_removed'), ('posting_key__isnull', False), ('source_id__isnull', True)), _connector='OR'), name='cash_movement_evidence_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('business', 'movement_type', 'source_id'), name='cash_unique_movement_source_per_business'),
        ),
        migrations.AddConstraint(
            model_name='cashsessionclosure',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='cash_unique_closure_sequence_per_session'),
        ),
        migrations.AddConstraint(
            model_name='cashsessionclosure',
            constraint=models.CheckConstraint(condition=models.Q(('expected_cash__gte', Decimal('0.00'))), name='cash_closure_expected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashsessionclosure',
            constraint=models.CheckConstraint(condition=models.Q(('actual_cash__gte', Decimal('0.00'))), name='cash_closure_actual_nonnegative'),
        ),
    ]
