# Generated by Django 5.2.16 on 2026-09-12 13:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_businessmembership_role'),
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='cash_movement_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='cashmovement',
            name='cash_movement_evidence_matches_type',
        ),
        migrations.AddField(
            model_name='cashsession',
            name='opening_basis_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_float', 'Opening float'), ('cash_sale', 'Cash sale'), ('cash_refund', 'Cash refund'), ('cash_added', 'Cash added'), ('cash_removed', 'Cash removed'), ('operating_expense', 'Operating expense'), ('operating_expense_reversal', 'Operating expense reversal'), ('supplier_payment', 'Supplier payment'), ('supplier_payment_reversal', 'Supplier payment reversal'), ('supplier_refund', 'Supplier refund recovered'), ('supplier_refund_reversal', 'Supplier refund reversal')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['opening_float', 'cash_sale', 'cash_refund', 'cash_added', 'cash_removed', 'operating_expense', 'operating_expense_reversal', 'supplier_payment', 'supplier_payment_reversal', 'supplier_refund', 'supplier_refund_reversal'])), name='cash_movement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_delta__gte', Decimal('0.00')), ('movement_type', 'opening_float'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'cash_sale'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'cash_refund'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'cash_added'), ('posting_key__isnull', False), ('source_id__isnull', True)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'cash_removed'), ('posting_key__isnull', False), ('source_id__isnull', True)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'operating_expense'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'operating_expense_reversal'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'supplier_payment'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'supplier_payment_reversal'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__gt', Decimal('0.00')), ('movement_type', 'supplier_refund'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), models.Q(('amount_delta__lt', Decimal('0.00')), ('movement_type', 'supplier_refund_reversal'), ('posting_key__isnull', True), ('reason', ''), ('source_id__isnull', False)), _connector='OR'), name='cash_movement_evidence_matches_type'),
        ),
    ]
